Repository whispia/whispia-server, pull requests merged in 2025-08, with the labels that each got.

#15 [REFACTOR] liquibase DDL yaml -> sql 방식으로 이관
  whispia-common/src/main/kotlin/com/whispia/common/global/config/LiquibaseIncludeAllFilter.kt
  whispia-common/src/main/resources/liquibase/changelog/V001_create_table_users.sql
  whispia-common/src/main/resources/liquibase/changelog/V001_create_table_users.yaml
  whispia-common/src/main/resources/liquibase/changelog/V002_create_table_worries.sql
  whispia-common/src/main/resources/liquibase/changelog/V002_create_table_worries.yaml
  whispia-common/src/main/resources/liquibase/changelog/V003_create_table_chat_rooms.sql
  whispia-common/src/main/resources/liquibase/changelog/V003_create_table_chat_rooms.yaml
  whispia-common/src/main/resources/liquibase/changelog/V004_create_table_chat_messages.sql
  whispia-common/src/main/resources/liquibase/changelog/V004_create_table_chat_messages.yaml
  whispia-common/src/main/resources/liquibase/changelog/V005_create_table_reports.sql
  whispia-common/src/main/resources/liquibase/changelog/V005_create_table_reports.yaml
Labels: refactor

#16 [FEAT] 엔티티 클래스 설계
  whispia-api/src/main/kotlin/com/whispia/api/chatmessage/domain/ChatMessage.kt
  whispia-api/src/main/kotlin/com/whispia/api/chatmessage/domain/ChatMessageStatus.kt
  whispia-api/src/main/kotlin/com/whispia/api/chatroom/domain/ChatRoom.kt
  whispia-api/src/main/kotlin/com/whispia/api/report/domain/Report.kt
  whispia-api/src/main/kotlin/com/whispia/api/report/domain/ReportType.kt
  whispia-api/src/main/kotlin/com/whispia/api/user/domain/User.kt
  whispia-api/src/main/kotlin/com/whispia/api/user/domain/UserStatus.kt
  whispia-api/src/main/kotlin/com/whispia/api/worry/domain/Worry.kt
  whispia-api/src/main/kotlin/com/whispia/api/worry/domain/WorryCategory.kt
  whispia-api/src/main/kotlin/com/whispia/api/worry/domain/WorryStatus.kt
  whispia-common/build.gradle
  whispia-common/src/main/kotlin/com/whispia/common/global/config/JpaAuditingConfig.kt
  whispia-common/src/main/kotlin/com/whispia/common/global/domain/BaseEntity.kt
Labels: feature

#19 [CHORE] 로컬 소나큐브 설정
  build.gradle
  infra/docker-compose.yml
  whispia-common/src/test/kotlin/com/whispia/common/WhispiaCommonApplicationTests.kt
Labels: chore

#21 [REFACTOR] 초기 스키마 고도화
  build.gradle
  whispia-api/build.gradle
  whispia-api/src/main/kotlin/com/whispia/api/chat/chatroom/domain/ChatRoom.kt
  whispia-api/src/main/kotlin/com/whispia/api/chat/message/domain/ChatMessage.kt
  whispia-api/src/main/kotlin/com/whispia/api/chat/message/domain/ChatMessageStatus.kt
  whispia-api/src/main/kotlin/com/whispia/api/chatmessage/domain/ChatMessageStatus.kt
  whispia-api/src/main/kotlin/com/whispia/api/report/domain/Report.kt
  whispia-api/src/main/kotlin/com/whispia/api/report/domain/ReportType.kt
  whispia-api/src/main/kotlin/com/whispia/api/user/domain/User.kt
  whispia-api/src/main/kotlin/com/whispia/api/worry/domain/Worry.kt
  whispia-api/src/main/kotlin/com/whispia/api/worry/domain/WorryCategory.kt
  whispia-api/src/test/kotlin/com/whispia/api/WhispiaApiApplicationTest.kt
  whispia-api/src/test/kotlin/com/whispia/api/chat/chatroom/domain/ChatRoomTest.kt
  whispia-api/src/test/kotlin/com/whispia/api/chat/message/domain/ChatMessageTest.kt
  whispia-api/src/test/kotlin/com/whispia/api/report/domain/ReportTest.kt
  whispia-api/src/test/kotlin/com/whispia/api/user/domain/UserTest.kt
  whispia-api/src/test/kotlin/com/whispia/api/worry/domain/WorryTest.kt
  whispia-api/src/test/resources/application-test.yml
  whispia-common/build.gradle
  whispia-common/src/main/kotlin/com/whispia/common/global/domain/BaseEntity.kt
  whispia-common/src/main/kotlin/com/whispia/common/global/dto/ResponseData.kt
  whispia-common/src/main/kotlin/com/whispia/common/global/exception/GlobalErrorHandler.kt
  whispia-common/src/main/resources/liquibase/changelog/V001_create_table_users.sql
  whispia-common/src/main/resources/liquibase/changelog/V002_create_table_worries.sql
  whispia-common/src/main/resources/liquibase/changelog/V003_create_table_chat_rooms.sql
  whispia-common/src/main/resources/liquibase/changelog/V004_create_table_chat_messages.sql
  whispia-common/src/main/resources/liquibase/changelog/V005_create_table_reports.sql
  whispia-common/src/test/kotlin/com/whispia/common/global/exception/GlobalErrorHandlerTest.kt
Labels: refactor

#25 [WHISPIA-11] 로컬 모니터링, 로깅 설정을 위한 도커 컨테이너 생성
  build.gradle
  infra/config/loki-config.yml
  infra/config/prometheus.yml
  infra/config/promtail-config.yml
  infra/docker-compose.yml
  whispia-api/build.gradle
  whispia-api/src/main/resources/application-local.yml
  whispia-chat/build.gradle
  whispia-chat/src/main/resources/application-local.yml
Labels: chore

#26 [WHISPIA-2] 고민 등록 API 생성
  whispia-api/build.gradle
  whispia-api/src/main/kotlin/com/whispia/api/WhispiaApiApplication.kt
  whispia-api/src/main/kotlin/com/whispia/api/global/config/QueryDslConfig.kt
  whispia-api/src/main/kotlin/com/whispia/api/global/handler/GlobalErrorHandler.kt
  whispia-api/src/main/kotlin/com/whispia/api/user/domain/repository/UserRepository.kt
  whispia-api/src/main/kotlin/com/whispia/api/user/infrastructure/UserJpaRepository.kt
  whispia-api/src/main/kotlin/com/whispia/api/user/infrastructure/UserRepositoryImpl.kt
  whispia-api/src/main/kotlin/com/whispia/api/worry/application/WorrySaveService.kt
  whispia-api/src/main/kotlin/com/whispia/api/worry/application/WorrySaveServiceImpl.kt
  whispia-api/src/main/kotlin/com/whispia/api/worry/application/dto/WorrySaveInput.kt
  whispia-api/src/main/kotlin/com/whispia/api/worry/application/dto/WorrySaveRequest.kt
  whispia-api/src/main/kotlin/com/whispia/api/worry/domain/WorryStatus.kt
  whispia-api/src/main/kotlin/com/whispia/api/worry/domain/repository/WorryRepository.kt
  whispia-api/src/main/kotlin/com/whispia/api/worry/infrastructure/WorryJpaRepository.kt
  whispia-api/src/main/kotlin/com/whispia/api/worry/infrastructure/WorryRepositoryImpl.kt
  whispia-api/src/main/kotlin/com/whispia/api/worry/presentation/WorryApiController.kt
  whispia-api/src/test/kotlin/com/whispia/api/WhispiaApiApplicationTest.kt
  whispia-api/src/test/kotlin/com/whispia/api/chat/chatroom/domain/ChatRoomTest.kt
  whispia-api/src/test/kotlin/com/whispia/api/chat/message/domain/ChatMessageTest.kt
  whispia-api/src/test/kotlin/com/whispia/api/global/BaseTestContainer.kt
  whispia-api/src/test/kotlin/com/whispia/api/global/handler/GlobalErrorHandlerTest.kt
  whispia-api/src/test/kotlin/com/whispia/api/report/domain/ReportTest.kt
  whispia-api/src/test/kotlin/com/whispia/api/user/domain/UserTest.kt
  whispia-api/src/test/kotlin/com/whispia/api/worry/domain/WorryTest.kt
  whispia-api/src/test/resources/application-test.yml
  whispia-common/build.gradle
  whispia-common/src/test/resources/application.yml
Labels: feature

#28 [WHISPIA-20] 레디스 캐시 설정
  infra/docker-compose.yml
  whispia-api/build.gradle
  whispia-api/src/main/kotlin/com/whispia/api/WhispiaApiApplication.kt
  whispia-api/src/main/kotlin/com/whispia/api/global/config/CacheConfig.kt
  whispia-api/src/main/kotlin/com/whispia/api/global/config/CacheName.kt
  whispia-api/src/main/kotlin/com/whispia/api/global/config/CacheType.kt
  whispia-api/src/main/kotlin/com/whispia/api/worry/application/WorrySearchService.kt
  whispia-api/src/main/kotlin/com/whispia/api/worry/domain/Worry.kt
  whispia-api/src/main/resources/application-local.yml
  whispia-common/src/main/kotlin/com/whispia/common/global/model/dto/PaginationInput.kt
Labels: feature
